config/routes.rb
RavenDemo::Application.routes.draw do

  devise_for :users

  resources :messages

  resources :users

   root :to => 'home#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/message.rb
class Message < ActiveRecord::Base

validates :Messagetext, :presence =>true
validates :Latitude, :presence =>true
validates :Longitude, :presence =>true
validates :Sendername, :presence =>true
validates :Recepientname, :presence =>true


after_save do |message|
    
    puts "#########TEST######## " 
    ServerFactory::SURFBOARD.send_request("?req=addMarker&position=#{message.latitude},#{message.longitude}")
    puts "#####TEST####"
  end
end

app/models/server_factory.rb
class ServerFactory

  SURFBOARD = SurfboardClient.new(
      "mk@breakingwavesoftware.com",
      "mk_bws123!",
      "Surfboard"
  )
end

app/models/surfboard_client.rb
require 'patron'

class SurfboardClient

  AUTH_URL = 'https://www.google.com/accounts/ClientLogin'
  LOGIN_URL = 'http://bws-surfboard.appspot.com/_ah/login'
  SERVICE_URL = 'http://bws-surfboard.appspot.com/service'
  HTTP_TXN_TIMEOUT_SECONDS = 50

  def initialize (email, password, app_name)
    @email = email
    @password = password
    @app_name = app_name
    @session = Patron::Session.new
    @session.timeout = HTTP_TXN_TIMEOUT_SECONDS
  end

  # Sends a request and gets back the response. Does not rescue from any exceptions.
  # The data is url-encoded. The parts of the data that are already url-ish are left
  # as they are.
  def send_request (data)
    if (@auth_cookie.nil?)
      login
    end

    if (@auth_cookie)
      @session.base_url = SERVICE_URL
      resp = @session.get(URI.escape(data), {"Cookie" => @auth_cookie})

      puts "########send request", resp

      return resp.body
      
    end
  end

  private

  def login
    auth_token = get_auth_token

    if (auth_token)
      @session.base_url = LOGIN_URL
      
      puts "##########Starting login"

      resp = @session.get("?auth=" + auth_token)
	puts resp.body
      auth_cookie = resp.headers["Set-Cookie"]

      if (auth_cookie && auth_cookie[0][0,6] == "ACSID=")
        @auth_cookie = auth_cookie[0]
      end
    end
  end

  def get_auth_token
    @session.base_url = AUTH_URL
    data = "accountType=GOOGLE&Email=#{@email}&Passwd=#{@password}&service=ah&source=#{@app_name}"
    
	puts "check 1", data

    resp = @session.post("", data)
	puts "check 2", resp.body
    resp.body.each_line do |line|
      if (line[0,5] == "Auth=")
        return (line[5, line.length - 1])
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
validates :name, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RavenDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :messagetext %><br />
    <%= f.text_area :messagetext %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :sendername %><br />
    <%= f.text_field :sendername %>
  </div>
  <div class="field">
    <%= f.label :recipientname %><br />
    <%= f.text_field :recipientname %>
  </div>
  <div class="field">
    <%= f.label :sentat %><br />
    <%= f.datetime_select :sentat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Messagetext</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Sendername</th>
    <th>Recipientname</th>
    <th>Sentat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.messagetext %></td>
    <td><%= message.latitude %></td>
    <td><%= message.longitude %></td>
    <td><%= message.sendername %></td>
    <td><%= message.recipientname %></td>
    <td><%= message.sentat %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Messagetext:</b>
  <%= @message.messagetext %>
</p>

<p>
  <b>Latitude:</b>
  <%= @message.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @message.longitude %>
</p>

<p>
  <b>Sendername:</b>
  <%= @message.sendername %>
</p>

<p>
  <b>Recipientname:</b>
  <%= @message.recipientname %>
</p>

<p>
  <b>Sentat:</b>
  <%= @message.sentat %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>